# Generated by Django 4.1.5 on 2023-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DjangoAPIapp", "0002_alter_book_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
